spring:
  application:
    name: voting-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:  
      uri: ${MONGODB_URI:mongodb://localhost:27017/voting_db}  

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWTSECRET}         
    expire-ms: 3600000           
  cors:
    allowed-origins:
      - http://localhost:3000    
    allowed-methods:
      - GET
      - POST
  db:
    reset:
      enabled: ${DB_RESET_ENABLED:true}
      fixed-account-password: ${FIXED_ACCOUNT_PASSWORD}


management:
    endpoints:
      web:
        exposure:
          include: health,info
        base-path: /actuator
    endpoint:
      health:
        show-details: when-authorized

logging:
  level:
    root: INFO                   
